### ISSUE TITLE
40104:incorrect signature with parameter in API

### ISSUE THREAD

**Issue by joshuaavalon** [clsung/plurk-oauth#8]
```python
from plurk_oauth import PlurkAPI
import json

plurk = PlurkAPI.fromfile("keys.json")
jsonR = plurk.callAPI('/APP/Profile/getOwnProfile')
print(json.dumps(jsonR, sort_keys=True, indent=4))
jsonR = plurk.callAPI('/APP/Profile/getPublicProfile', {"user_id": <userid>})
print(json.dumps(jsonR, sort_keys=True, indent=4))
```

The first one return fine but  those with parameters return `None` and the error is `40104:incorrect signature`

**Comment by clsung** [comment]
Thanks for report this issue, I'm investigating it.

**Comment by joshuaavalon** [comment]
@clsung I found the problem.
https://github.com/clsung/plurk-oauth/blob/42dc98a5ea85b23ddef3b5cffcab48c93b0200e5/plurk_oauth/oauth.py#L96

If you remove `headers=req.to_header()`, the request is fine.

Also, after diving in the oauth2 source code, the following is useless.
https://github.com/clsung/plurk-oauth/blob/42dc98a5ea85b23ddef3b5cffcab48c93b0200e5/plurk_oauth/oauth.py#L65

`client.request` will sign and add the appropriate headers. You pass `req.to_header()` actually overwrite it with wrong headers.
